// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	http "github.com/go-kit/kit/transport/http"
	mux "github.com/gorilla/mux"
	endpoint "github.com/iampato/inventory/user/pkg/endpoint"
	http1 "net/http"
)

// NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := mux.NewRouter()
	makeCreateRoleHandler(m, endpoints, options["CreateRole"])
	makeFetchAllRolesHandler(m, endpoints, options["FetchAllRoles"])
	makeCreateHandler(m, endpoints, options["Create"])
	makeFetchAllUsersHandler(m, endpoints, options["FetchAllUsers"])
	return m
}
